import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronRight, ClipboardList, Heart, Home, Lightbulb, Menu, Play, Plus, RotateCcw, ShoppingBag, Sparkles, X} from 'lucide-react';
import {STORAGE_KEY,PROJECT_NAME,RESALE_LOW,RESALE_HIGH,EXAMPLE_CONSUMABLES,FURNITURE,SOURCES,FINISHES,PROBLEMS,CHOICE_IMAGES,DEFAULT_DEMO,PRODUCTS,getStages,getScore,getConcerns,formatMoney,finishWording,repairSupplyNames} from './demo';
import './styles.css';

const HERO = '/images/dresser-editorial.png';
const deepCopy = value => JSON.parse(JSON.stringify(value));
function loadDemo(){
  try {
    const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));
    if(saved && typeof saved==='object') return {...deepCopy(DEFAULT_DEMO),...saved,answers:{...DEFAULT_DEMO.answers,...saved.answers},listing:{...DEFAULT_DEMO.listing,...saved.listing}};
  } catch { /* A private browser can still use the demo in memory. */ }
  return deepCopy(DEFAULT_DEMO);
}
function fieldLabel(finish){return {'Paint it':'Painted finish','Restore the wood':'Restored wood finish','Paint + natural wood':'Paint + natural wood'}[finish];}

function App(){
  const [demo,setDemo]=useState(loadDemo);
  const [screen,setScreen]=useState('home');
  const [detail,setDetail]=useState(0);
  const [expanded,setExpanded]=useState(null);
  const [modal,setModal]=useState(null);
  const [chooseHelp,setChooseHelp]=useState(false);
  const [copied,setCopied]=useState(false);
  useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(demo))}catch{/* Browsing still works without storage. */}},[demo]);

  const stages=getStages(demo.finish,demo.problems);
  const completed=stages.filter(stage=>stage.tasks.every(task=>!!demo.checked[task.id])).length;
  const firstIncomplete=Math.max(0,stages.findIndex(stage=>!stage.tasks.every(task=>!!demo.checked[task.id])));
  const concerns=getConcerns(demo.answers);
  const purchase=Math.max(0,Number(demo.price)||0);
  const investment=purchase+EXAMPLE_CONSUMABLES;
  const profitLow=RESALE_LOW-investment, profitHigh=RESALE_HIGH-investment;
  const score=getScore(demo.answers,purchase);
  const thinMargin=profitLow<=0;
  const lowScore=score<65 || concerns.length>0 || thinMargin;
  const scoreReasons=[...concerns,demo.answers.style==='Very ornate / niche'?'a niche style':null,demo.answers.material==='Quality laminate'?'laminate material':null,demo.answers.condition==='Some repair needed'?'additional repair work':null,demo.answers.construction==='Needs a little tightening'?'construction needing attention':null].filter(Boolean);
  const relevantProducts=PRODUCTS.filter(product=>product.finishes.includes(demo.finish));
  const consumables=relevantProducts.filter(product=>product.category==='consumable');
  const equipment=relevantProducts.filter(product=>product.category==='equipment');
  const evaluated=!!demo.checked['evaluate-assessment'];
  const openStage=expanded===null?firstIncomplete:expanded;

  const update=(key,value)=>setDemo(current=>({...current,[key]:value}));
  const updateListing=(key,value)=>setDemo(current=>({...current,listing:{...current.listing,[key]:value}}));
  const go=next=>{setScreen(next);if(next==='plan')setExpanded(null);window.scrollTo({top:0,behavior:'smooth'})};
  const openDemo=()=>go(evaluated?'plan':'new');
  const toggleTask=id=>setDemo(current=>({...current,checked:{...current.checked,[id]:!current.checked[id]}}));
  const toggleProblem=value=>setDemo(current=>({...current,problems:current.problems.includes(value)?current.problems.filter(item=>item!==value):[...current.problems,value]}));
  const toggleOwned=id=>setDemo(current=>({...current,owned:current.owned.includes(id)?current.owned.filter(item=>item!==id):[...current.owned,id]}));
  const assess=()=>{setDemo(current=>({...current,checked:{...current.checked,'evaluate-assessment':true}}));go('makeover')};
  const chooseFinish=finish=>{
    if(finish===demo.finish)return;
    const affected=stages.filter(stage=>['Prep','Finish','Protect'].includes(stage.name)).flatMap(stage=>stage.tasks).filter(task=>task.id!=='prep-photo'&&demo.checked[task.id]);
    if(affected.length){setModal({kind:'finish',finish,affected});return}
    update('finish',finish);
  };
  const confirmFinish=()=>{
    setDemo(current=>{
      const next={...current.checked};
      [...getStages(current.finish,current.problems),...getStages(modal.finish,current.problems)]
        .filter(stage=>['Prep','Finish','Protect'].includes(stage.name))
        .flatMap(stage=>stage.tasks).filter(task=>task.id!=='prep-photo').forEach(task=>delete next[task.id]);
      return {...current,finish:modal.finish,checked:next};
    });
    setModal(null);
  };
  const reset=()=>{setDemo(deepCopy(DEFAULT_DEMO));setModal(null);setChooseHelp(false);setCopied(false);go('home')};
  const makeDraft=()=>{
    const fields=demo.listing;
    const title=`Mid-Century Dresser — ${fieldLabel(demo.finish)}`;
    const description=[
      `${PROJECT_NAME} with ${finishWording(demo.finish)}.${fields.finishColor?` Finish/color: ${fields.finishColor}.`:' Finish/color: [add verified finish and color].'}`,
      `Dimensions: ${fields.dimensions||'[add measured width × depth × height]'}`,
      `Condition and imperfections: ${fields.condition||'[describe the actual condition and any imperfections]'}`,
      `Pickup: ${fields.pickup||'[add pickup location and arrangements]'}`,
      `Asking price: ${formatMoney(Math.max(0,Number(fields.askingPrice)||0))}`
    ].join('\n\n');
    setDemo(current=>({...current,listing:{...current.listing,title,description}}));
    setCopied(false);
  };
  const copyDraft=async()=>{
    try{await navigator.clipboard.writeText(`${demo.listing.title}\n\n${demo.listing.description}`);setCopied(true)}catch{setCopied(false)}
  };

  const back=target=><button className="back" onClick={()=>go(target)}><ArrowLeft size={18}/> Back</button>;
  const title=(eyebrow,heading,sub)=><div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{heading}</h1>{sub&&<p>{sub}</p>}</div>;
  const pageHero=(photo,caption,alt)=><figure className="page-hero"><img src={`/images/heroes/${photo}.jpg`} alt={alt}/><figcaption>{caption}</figcaption></figure>;
  const button=(label,onClick,variant='primary',icon=true)=><button className={`button ${variant}`} onClick={onClick}>{label}{icon&&<ArrowRight size={18}/>}</button>;
  const choice=(value,selected,onClick,{image=false,disabled=false}={})=><button key={value} type="button" className={`choice ${selected?'selected':''} ${image?'with-image':''} ${disabled?'unavailable':''}`} aria-pressed={selected} aria-label={disabled?`${value}. Not available in this demo.`:value} disabled={disabled} onClick={onClick}>{image&&<img className="choice-icon" src={`/images/choices/${CHOICE_IMAGES[value]}.png`} alt=""/>}<span className="choice-label">{value}{disabled&&<small className="disabled-caption">Not available in this demo</small>}</span><span className="radio">{selected&&<Check size={13}/>}</span></button>;
  const tip=copy=><div className="tip"><div className="tip-icon"><Lightbulb size={17}/></div><div><strong>Catie’s Tip <small>· draft</small></strong><p>{copy}</p><span className="tip-review">Sample guidance for creator review</span></div></div>;
  const taskList=tasks=><div className="detail-checklist">{tasks.map(item=><label className="task" key={item.id}><input type="checkbox" checked={!!demo.checked[item.id]} onChange={()=>toggleTask(item.id)}/><span className="check-box"><Check size={13}/></span><span>{item.label}</span></label>)}</div>;
  const lessonCard=(stage,compact=false)=><div className={`lesson-card ${compact?'compact':''}`}><div className="lesson-icon"><Play size={16} fill="currentColor"/></div><div><strong className="lesson-heading">Catie shows you how</strong><span className="eyebrow">SAMPLE LESSON TITLE · CONFIRM WITH CATIE</span><h3>{stage.lesson}</h3>{!compact&&<p>Relevant to the {stage.name.toLowerCase()} stage of this dresser project.</p>}<button onClick={()=>setModal({kind:'lesson',title:stage.lesson})}>Watch This Lesson <ArrowRight size={15}/></button></div></div>;
  const productCard=product=><article className="product-card" key={product.id}><div className="product-image"><img src={`/images/${product.id}.png`} alt={product.name}/></div><div className="product-copy"><span className="mini-label">{product.category==='consumable'?'SAMPLE CONSUMABLE':'OPTIONAL REUSABLE TOOL'}</span><h2>{product.name}</h2><small>{product.brand}</small><p>{product.note}</p><div className="product-actions"><a href={product.url} target="_blank" rel="noopener noreferrer">View Product <ArrowRight size={15}/></a><button onClick={()=>toggleOwned(product.id)}>{demo.owned.includes(product.id)?<CheckCircle2 size={15}/>:<Plus size={15}/>} {demo.owned.includes(product.id)?'In my kit':'Already Have This'}</button></div></div></article>;

  return <div className="site"><div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>go('home')} aria-label="Go home"><span className="brand-mark">m<span>✦</span></span><span>miss mae <em>revivals</em><small>FLIP COMPANION</small></span></button><span className="demo-badge">Interactive demo</span><button className="header-action" onClick={()=>go('flips')} aria-label="My flips"><Menu size={23}/></button></header>
    <main key={screen} className="content">
    {screen==='home'&&<>
      <section className="hero"><div className="hero-copy"><span className="eyebrow light">YOUR CREATIVE SIDEKICK</span><h1>Ready to flip<br/><i>something?</i></h1><p>From “should I buy it?” to “sold!” — a little guidance for every step.</p>{button('Try the Dresser Demo',openDemo,'cream')}<p className="hero-notice">This prototype follows one sample dresser from purchase to listing. Explore the steps, supplies, and selling tools.</p></div><div className="hero-image"><img src={HERO} alt="Refinished mid-century dresser in a warm room"/></div></section>
      <div className="section-heading"><div><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>Your current flip</h2></div><button className="text-link" onClick={()=>go('flips')}>View all <ArrowRight size={15}/></button></div>
      <button className="project-card" onClick={openDemo}><img src={HERO} alt="Mid-Century Dresser"/><div><span className="mini-label">SAMPLE PROJECT</span><h3>{PROJECT_NAME}</h3><p>{completed} of 7 stages complete</p><div className="progress"><span style={{width:`${completed/7*100}%`}}/></div><span className="continue">Continue the demo <ArrowRight size={16}/></span></div></button>
      <div className="section-heading help-head"><div><span className="eyebrow">A LITTLE HELP, RIGHT ON TIME</span><h2>Quick help</h2></div></div><div className="help-grid">{[['Is this piece worth buying?','evaluation'],['What supplies do I need?','supplies'],['How should I refinish this?','makeover'],['How should I price it?','sell']].map(([text,where],i)=><button className="help-card" key={text} onClick={()=>go(where)}><span className="help-number">0{i+1}</span><strong>{text}</strong><ArrowRight size={18}/></button>)}</div>
      <div className="home-note"><Sparkles size={18}/><span>Made for the magic in the messy middle.</span></div>
    </>}
    {screen==='new'&&<>{back('home')}{title('LET’S GET STARTED','Tell me about your find.','We’re following one sample dresser through the full flip.')}{pageHero('found-dresser','A FIND WITH POTENTIAL','Sample wood dresser waiting to be refinished')}
      <div className="demo-explainer">We’re using one dresser so you can experience the complete workflow. Additional furniture types can be added later.</div>
      <div className="form-section"><div className="question-head"><span>01</span><h2>What are you flipping?</h2></div><div className="choice-grid">{FURNITURE.map(value=>choice(value,value==='Dresser',()=>{}, {image:true,disabled:value!=='Dresser'}))}</div></div>
      <div className="form-section"><div className="question-head"><span>02</span><h2>Where did you find it?</h2></div><div className="choice-grid">{SOURCES.map(value=>choice(value,demo.source===value,()=>update('source',value),{image:true}))}</div></div>
      <div className="form-section"><div className="question-head"><span>03</span><h2>What’s the purchase price?</h2></div><label className="price-input"><span>$</span><input type="number" min="0" value={demo.price} onChange={e=>update('price',e.target.value)} aria-label="Purchase price"/><small>USD</small></label><p className="field-hint">Free find? Enter $0.</p></div>{button('Evaluate This Dresser',()=>go('evaluation'))}</>}
    {screen==='evaluation'&&<>{back('new')}{title('BUY THIS, NOT THAT','Is it a good flip?','Explore how the proposed dresser evaluation could work.')}{pageHero('found-dresser','LOOK CLOSER BEFORE YOU BUY','Sample dresser with light wear')}
      <div className="eval-intro"><div className="intro-icon"><ClipboardList size={22}/></div><div><strong>{PROJECT_NAME}</strong><p>{demo.source} · Purchase {formatMoney(purchase)}</p></div></div>
      {[['style','Style',['Mid-century / clean lines','Vintage / classic','Very ornate / niche']],['material','Material',['Solid wood or veneer','Quality laminate','Particle board / MDF']],['condition','Condition',['Minor cosmetic wear','Some repair needed','Major repairs needed']],['construction','Construction',['Sturdy and stable','Needs a little tightening','Wobbly or damaged']]].map(([key,label,options],i)=><div className="eval-group" key={key}><div className="question-head"><span>0{i+1}</span><h2>{label}</h2></div><div className="stacked-choices">{options.map(value=>choice(value,demo.answers[key]===value,()=>update('answers',{...demo.answers,[key]:value})))}</div></div>)}
      <div className={`result-card ${lowScore?'caution':''}`}><div className="result-top"><span><Sparkles size={17}/> {lowScore?'CONSIDER PASSING':'GOOD FLIP POTENTIAL'}</span><strong>{score}<small>/100</small></strong></div><h2>{lowScore?(concerns.length?'This dresser may need more than a quick flip.':thinMargin?'The purchase price leaves too little room.':'This dresser needs a closer look.'):'This dresser has promise.'}</h2><p>{lowScore?`${scoreReasons.length?`Selected concerns: ${scoreReasons.join(', ')}. `:''}${thinMargin?'The example investment leaves no margin at the low end of the resale range. ':''}Inspect further before deciding to buy.`:'The sample answers suggest a practical project with mostly cosmetic work.'}</p><div className="score-disclaimer"><strong>Demo flip score</strong><span>Illustrates a proposed evaluation tool. It is not a validated valuation model.</span></div></div>
      <div className="example-box"><span className="eyebrow">SEPARATE EXAMPLE CALCULATION</span><h2>Sample dresser numbers</h2><div className="example-grid"><div><span>Purchase</span><strong>{formatMoney(purchase)}</strong></div><div><span>Example consumables</span><strong>$35</strong></div><div><span>Example investment</span><strong>{formatMoney(investment)}</strong></div><div><span>Illustrative resale range</span><strong>$275–$375</strong></div><div className="wide"><span>Illustrative gross profit</span><strong>{formatMoney(profitLow)}–{formatMoney(profitHigh)}</strong></div></div><p>The $35 example excludes reusable equipment, extra repair materials, fees, and labor. These figures are illustrations, not predictions.</p>{concerns.length>0&&<div className="caution-note">These sample figures assume a sturdy dresser with minor cosmetic repairs. They do not account for the additional problems you selected. Do not treat the example profit as a reliable opportunity for this piece.</div>}</div>
      {button('Save Evaluation & Choose Makeover',assess)}</>}
    {screen==='makeover'&&<>{back('evaluation')}{title('MAKEOVER DIRECTION','What’s the vision?','Select one of three preset dresser plans.')}{pageHero('workshop','THE POSSIBILITIES ARE GOOD','Dresser being carefully sanded in a workshop')}
      <div className="form-section"><div className="question-head"><span>01</span><h2>Choose a makeover</h2></div><div className="stacked-choices">{FINISHES.map(value=>choice(value,demo.finish===value,()=>chooseFinish(value)))}</div><button className="help-choose" onClick={()=>setChooseHelp(!chooseHelp)} aria-expanded={chooseHelp}>Help me choose <ChevronRight size={16}/></button>{chooseHelp&&<div className="help-choose-panel"><p><strong>Paint it</strong> gives the dresser a new painted surface.</p><p><strong>Restore the wood</strong> focuses on the existing wood finish and veneer.</p><p><strong>Paint + natural wood</strong> combines painted areas with visible wood.</p><p>Select one of the three approaches above to build the plan.</p></div>}</div>
      <div className="form-section"><div className="question-head"><span>02</span><h2>What’s the current surface?</h2></div><div className="choice-grid">{['Previously finished wood','Bare wood','Previously painted','Laminate / other'].map(value=>choice(value,demo.surface===value,()=>update('surface',value)))}</div></div>
      <div className="form-section"><div className="question-head"><span>03</span><h2>Any problem spots?</h2></div><p className="field-hint top">Select all that apply. Only selected problems add repair tasks.</p><div className="chip-grid">{PROBLEMS.map(value=><button key={value} className={`chip ${demo.problems.includes(value)?'active':''}`} aria-pressed={demo.problems.includes(value)} onClick={()=>toggleProblem(value)}>{demo.problems.includes(value)&&<Check size={14}/>} {value}</button>)}</div></div>{tip('Choose a finish after looking closely at the current surface and how much repair it needs.')}{button('View My Dresser Plan',()=>go('plan'))}</>}
    {screen==='plan'&&<>{back('flips')}{title('YOUR PERSONAL ROADMAP','Your Dresser Flip Plan','Seven stages, with one checklist shared across the plan and step details.')}{pageHero('workshop','FROM FIND TO FINISH','Furniture restoration in progress')}
      <div className="plan-summary"><div><span className="eyebrow light">PROJECT PROGRESS</span><h2>{completed} of 7 stages<br/>complete</h2></div><div className="ring" style={{'--progress':`${completed/7*100}%`}}><span>{Math.round(completed/7*100)}%</span></div><div className="plan-progress"><span style={{width:`${completed/7*100}%`}}/></div></div>
      <div className="plan-toolbar"><span className="path-label">EVALUATE → PREP → REPAIR → FINISH → PROTECT → STYLE → SELL</span><button onClick={()=>go('makeover')}>Change finish</button></div>
      {button(completed===7?'Review Selling Tools':`Continue: ${stages[firstIncomplete].name}`,()=>{if(completed===7)go('sell');else{setDetail(firstIncomplete);go(firstIncomplete===6?'sell':'detail')}})}
      <div className="phase-list">{stages.map((stage,i)=>{const done=stage.tasks.filter(item=>demo.checked[item.id]).length;const isOpen=openStage===i;return <div className="phase-card" key={stage.name}><button className="phase-main" onClick={()=>setExpanded(isOpen?-1:i)} aria-expanded={isOpen}><span className={`phase-number ${done===stage.tasks.length?'complete':''}`}>{done===stage.tasks.length?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><span className="phase-copy"><small>{stage.kicker}</small><strong>{stage.name}</strong></span><span className="phase-count">{done}/{stage.tasks.length}</span><ChevronRight className={isOpen?'rotate-down':''} size={18}/></button>{isOpen&&<div className="phase-body">{taskList(stage.tasks)}<button className="inline-supply" onClick={()=>{setDetail(i);go(i===6?'sell':'detail')}}>Open {stage.name} step <ArrowRight size={15}/></button>{['Prep','Finish','Protect'].includes(stage.name)&&<button className="inline-supply" onClick={()=>go('supplies')}><ShoppingBag size={16}/> Supplies for this plan <ArrowRight size={15}/></button>}</div>}</div>})}</div><p className="draft-note">Refinishing steps and tips are draft sample guidance for Catie’s review.</p></>}
    {screen==='detail'&&<>{back('plan')}<div className="detail-tag">STEP {String(detail+1).padStart(2,'0')} OF 07</div>{title(stages[detail].kicker.toUpperCase(),stages[detail].name,`A practical guide to the ${stages[detail].name.toLowerCase()} stage.`)}{pageHero(detail===0?'found-dresser':detail>=5?'finished-dresser':detail>=3?'supplies':'workshop',`${stages[detail].name.toUpperCase()} IN PROGRESS`,'Dresser project at this stage')}
      <div className="time-card"><span>ESTIMATED ACTIVE TIME</span><strong>{stages[detail].time}</strong></div><div className="detail-section"><span className="mini-label">DRAFT SAMPLE GUIDANCE · FOR CREATOR REVIEW</span><h2>Here’s what to do</h2><p>{stages[detail].instructions}</p>{taskList(stages[detail].tasks)}</div>{tip(stages[detail].tip)}
      {['Prep','Repair','Finish','Protect'].includes(stages[detail].name)&&<button className="inline-supply" onClick={()=>go('supplies')}><ShoppingBag size={16}/> See supplies for this plan <ArrowRight size={15}/></button>}
      {lessonCard(stages[detail])}{button(detail===6?'Open Selling Tools':'Next Step',()=>{if(detail===6)go('sell');else{setDetail(detail+1);go('detail')}})}</>}
    {screen==='supplies'&&<>{back('plan')}{title('THE GOOD STUFF','Supplies for your flip.','Sample materials matched to your selected dresser plan.')}{pageHero('supplies','TOOLS FOR THE TRANSFORMATION','Sander, paint, brushes and furniture refinishing supplies')}
      <div className="supply-banner"><ShoppingBag size={22}/><div><strong>{fieldLabel(demo.finish)} plan</strong><p>{demo.problems.length?`Repair spots: ${demo.problems.join(', ')}`:'No repair spots selected'}</p></div></div>
      <div className="section-heading"><div><span className="eyebrow">SAMPLE PLAN MATERIALS</span><h2>Consumables</h2></div></div><p className="supply-note">The $35 example is a simple consumables allowance. Actual products and quantities, including extra repairs, may cost more.</p><div className="product-list">{consumables.map(productCard)}</div>
      {demo.problems.length>0&&<div className="repair-supplies"><strong>For your selected repairs</strong><ul>{repairSupplyNames(demo.problems).map(name=><li key={name}>{name}</li>)}</ul><p>Choose materials after inspecting the actual problem. Additional repair costs are outside the $35 example.</p></div>}
      <div className="section-heading"><div><span className="eyebrow">BUY ONCE, USE AGAIN</span><h2>Optional equipment</h2></div></div><p className="supply-note">Reusable equipment is not included in the $35 example.</p><div className="product-list">{equipment.map(productCard)}</div><p className="affiliate">Product suggestions are sample content for this prototype, not confirmed recommendations from Catie. Some links in a future Favorites collection may be affiliate links; no affiliate tracking is configured here.</p>{button('Back to My Dresser Plan',()=>go('plan'),'outline')}</>}
    {screen==='sell'&&<>{back('plan')}{title('THE FINISH LINE','Let’s get it listed.','The draft is yours to check, edit, and copy.')}{pageHero('finished-dresser','READY FOR ITS NEXT HOME','Finished dresser staged for a furniture listing')}
      <div className="sell-hero"><span className="eyebrow light">ILLUSTRATIVE DRESSER FIGURES</span><h2>{PROJECT_NAME}</h2><p className="sell-source">Found via {demo.source}</p><div className="money-row"><div><span>Purchase</span><strong>{formatMoney(purchase)}</strong></div><div><span>Example consumables</span><strong>$35</strong></div><div><span>Example investment</span><strong>{formatMoney(investment)}</strong></div></div><div className="resale-row"><div><span>Illustrative resale</span><strong>$275–$375</strong></div><div><span>Illustrative gross profit</span><strong>{formatMoney(profitLow)}–{formatMoney(profitHigh)}</strong></div></div><small>Examples, not predictions. Equipment, extra repairs, fees, and labor are excluded.</small></div>
      {concerns.length>0&&<div className="caution-note sell-caution">These sample figures assume a sturdy dresser with minor cosmetic repairs. They do not account for the additional problems you selected.</div>}
      <div className="detail-section"><h2>Ready-to-list checklist</h2>{taskList(stages[6].tasks)}</div>{tip(stages[6].tip)}
      <div className="listing-form"><span className="eyebrow">SAMPLE LISTING BUILDER</span><h2>Add the real details</h2><p>Unknown facts stay as placeholders. Verify every detail before posting.</p><label>Asking price <span>USD</span><input type="number" min="0" value={demo.listing.askingPrice} onChange={e=>updateListing('askingPrice',e.target.value)} placeholder="e.g. 375"/></label><label>Dimensions <span>measure the piece</span><input value={demo.listing.dimensions} onChange={e=>updateListing('dimensions',e.target.value)} placeholder="Width × depth × height"/></label><label>Finish / color <input value={demo.listing.finishColor} onChange={e=>updateListing('finishColor',e.target.value)} placeholder="Describe the actual finish and color"/></label><label>Condition and imperfections <textarea value={demo.listing.condition} onChange={e=>updateListing('condition',e.target.value)} placeholder="Describe what you can verify, including flaws"/></label><label>Pickup details <input value={demo.listing.pickup} onChange={e=>updateListing('pickup',e.target.value)} placeholder="Location and pickup arrangements"/></label><div className="listing-input-note">Demo inputs: {demo.source} find · {formatMoney(purchase)} purchase · {formatMoney(investment)} example investment. These costs stay out of buyer-facing copy.</div>{button(demo.listing.title?'Refresh Listing Draft':'Help Me Create My Listing',makeDraft)}</div>
      {demo.listing.title&&<div className="listing-card"><div className="listing-top"><span><Sparkles size={17}/> EDITABLE MARKETPLACE DRAFT</span></div><div className="draft-context">Project context: {demo.source} · {formatMoney(purchase)} purchase · {formatMoney(investment)} example investment. These private costs are not copied into the listing.</div><label>Title<input value={demo.listing.title} onChange={e=>updateListing('title',e.target.value)}/></label><label>Description<textarea rows="11" value={demo.listing.description} onChange={e=>updateListing('description',e.target.value)}/></label><p>Review measurements, condition, finish, and pickup details before posting. Refreshing the draft replaces edits.</p><button className="copy-button" onClick={copyDraft}>{copied?'Copied current draft!':'Copy listing text'}</button></div>}
    </>}
    {screen==='flips'&&<>{title('YOUR CREATIVE TRACK RECORD','My Flips','One sample dresser, ready to explore from purchase to listing.')}{pageHero('finished-dresser','EVERY FLIP HAS A STORY','Refinished dresser staged in a living room')}{button('Open Dresser Demo',openDemo)}<div className="section-heading"><div><span className="eyebrow">CURRENT DEMO PROJECT</span><h2>In the works</h2></div></div><button className="flip-tile" onClick={openDemo}><img src={HERO} alt="Mid-Century Dresser"/><div><span className="mini-label">ACTIVE DEMO</span><h3>{PROJECT_NAME}</h3><p>{completed}/7 stages complete</p><div className="progress"><span style={{width:`${completed/7*100}%`}}/></div></div><ChevronRight size={18}/></button><div className="section-heading"><div><span className="eyebrow">IN THE FULL VERSION</span><h2>Finished projects</h2></div></div><div className="empty-state">Completed projects would appear here in the full version. This demo follows only the current dresser and does not mark it sold when you create a listing draft.</div><button className="reset-action" onClick={()=>setModal({kind:'reset'})}><RotateCcw size={15}/> Reset Demo</button></>}
    {screen==='learn'&&<>{title('LEARN WITH CATIE','A little more know-how.','Preview how lessons could appear in the context of your project.')}{pageHero('workshop','SKILLS FOR EVERY STAGE','Hands refinishing a dresser in a home workshop')}
      <div className="learn-hero"><BookOpen size={27}/><span className="eyebrow light">SAMPLE COURSE LESSON LIBRARY</span><h2>Learn as you flip.</h2><p>These lesson titles are placeholders until Catie confirms the course structure. Preview access is shown below; video playback is not connected.</p></div><div className="section-heading"><div><span className="eyebrow">ORGANIZED BY PROJECT STAGE</span><h2>Sample lessons</h2></div></div><div className="lesson-library">{stages.map((stage,i)=><div key={stage.name}><span className="library-stage">{String(i+1).padStart(2,'0')} · {stage.name}</span>{lessonCard(stage,true)}</div>)}</div></>}
    </main>
    <nav className="bottom-nav" aria-label="Main navigation">{[['Home','home',Home],['My Flips','flips',Heart],['Learn','learn',BookOpen],['Supplies','supplies',ShoppingBag]].map(([label,where,Icon])=><button key={where} className={screen===where?'active':''} onClick={()=>go(where)}><Icon size={21} strokeWidth={screen===where?2.5:1.9}/><span>{label}</span></button>)}</nav>
  </div><div className="desktop-aside"><span>MISS MAE REVIVALS</span><h2>Find it.<br/>Flip it.<br/><i>Love it.</i></h2><p>Your hands-on companion for turning a promising find into a beautiful, profitable flip.</p><div className="aside-rule"/><small>INTERACTIVE DEMO · ONE SAMPLE DRESSER</small></div>
  {modal&&<div className="modal-backdrop" role="presentation" onClick={()=>setModal(null)}><div className="modal-panel" role="dialog" aria-modal="true" aria-label={modal.kind==='lesson'?'Lesson preview':modal.kind==='reset'?'Reset demo confirmation':'Change finish confirmation'} onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)} aria-label="Close dialog"><X size={19}/></button>{modal.kind==='lesson'?<><span className="eyebrow">SAMPLE LESSON TITLE · CONFIRM WITH CATIE</span><h2>Catie shows you how</h2><h3>{modal.title}</h3><div className="modal-video"><Play size={28} fill="currentColor"/><span>VIDEO PLACEHOLDER · NO PLAYBACK IN DEMO</span></div><p>In the full app, this opens the relevant course video included with your access. Video playback is not connected in this demo.</p>{button('Close Preview',()=>setModal(null),'outline',false)}</>:modal.kind==='reset'?<><span className="eyebrow">START FRESH</span><h2>Reset the dresser demo?</h2><p>This clears demo progress, owned supplies, listing edits, and changed selections. The starting dresser details will be restored.</p><div className="modal-actions">{button('Keep My Progress',()=>setModal(null),'outline',false)}{button('Reset Demo',reset,'primary',false)}</div></>:<><span className="eyebrow">PLAN CHANGE</span><h2>Switch to {modal.finish}?</h2><p>{modal.affected.length===1?'This completed task will reset':'These completed tasks will reset'} because the finish instructions change:</p><ul>{modal.affected.map(item=><li key={item.id}>{item.label}</li>)}</ul><p>Before photos, evaluation, repairs, styling, and selling progress will stay checked.</p><div className="modal-actions">{button('Keep Current Finish',()=>setModal(null),'outline',false)}{button('Change Finish',confirmFinish,'primary',false)}</div></>}</div></div>}
  </div>;
}

createRoot(document.getElementById('root')).render(<App/>);
