import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronDown, ChevronRight, ClipboardList, Heart, Home, Lightbulb, Menu, Play, Plus, ShoppingBag, Sparkles, Tag, X } from 'lucide-react';
import './styles.css';

const IMAGE = '/images/dresser-editorial.png';
const courseUrl = 'https://stan.store/missmaerevivals';
const types = ['Dresser','Nightstands','Buffet / Credenza','Entry / Sofa Table','Cabinet','Other'];
const sources = ['Facebook Marketplace','Thrift Store','Garage / Estate Sale','Curb / Free','Already Own It'];
const choiceImages = {'Dresser':'dresser','Nightstands':'nightstands','Buffet / Credenza':'buffet','Entry / Sofa Table':'table','Cabinet':'cabinet','Other':'other','Facebook Marketplace':'marketplace','Thrift Store':'thrift','Garage / Estate Sale':'estate','Curb / Free':'curb','Already Own It':'own'};
const problems = ['Scratches','Water stains','Chipped veneer','Loose hardware','Sticky drawers','Odor'];
const phases = [
  {name:'Evaluate', kicker:'Know your piece', tasks:['Confirm the piece is sturdy and worth the work','Photograph the before and note any damage'], tip:'Check every drawer, corner, and joint before you commit. A pretty front can hide a lot of extra work.', time:'15–20 min'},
  {name:'Prep', kicker:'A clean start', tasks:['Remove hardware and label each piece','Clean every surface thoroughly','Lightly scuff sand for adhesion'], tip:"Don’t start sanding until you’ve thoroughly cleaned the piece. Built-up furniture polish and grease can cause refinishing problems later.", time:'30–45 min'},
  {name:'Repair', kicker:'Fix the little things', tasks:['Fill scratches and small dents','Repair veneer and tighten loose hardware','Make sure drawers glide smoothly'], tip:'A few minutes fixing sticky drawers now can make the finished piece feel much more valuable.', time:'30–60 min'},
  {name:'Finish', kicker:'The transformation', tasks:['Apply the right primer if painting','Paint or refinish in thin, even coats','Let each coat dry fully'], tip:'Thin coats win. Rushing a heavy coat can leave drips and slow down the whole flip.', time:'1–2 hrs active'},
  {name:'Protect', kicker:'Make it last', tasks:['Choose a finish that suits the surface','Apply protective topcoat if needed','Allow the finish to cure'], tip:'Dry to the touch is not the same as fully cured. Give your piece the time it needs.', time:'20–40 min active'},
  {name:'Style', kicker:'The final details', tasks:['Clean and reinstall hardware','Stage with simple, neutral accessories','Take clear photos in natural light'], tip:'Let the furniture be the star. One or two simple styling pieces are enough.', time:'20–30 min'},
  {name:'Sell', kicker:'Ready for its next home', tasks:['Write a clear, honest listing','Set an asking price with room to negotiate','Post and respond to buyers'], tip:'Lead with your best photo and include dimensions. Buyers should know exactly what they’re getting.', time:'20–30 min'}
];
const products = [
  {id:'primer',name:'Oil-based primer',brand:'Zinsser Cover-Stain',note:'A dependable base when stains or old finishes might bleed through.',use:'Finish · if painting',url:'https://www.zinsseruk.com/product/cover-stain/'},
  {id:'paint',name:'Emerald Urethane Trim Enamel',brand:'Sherwin-Williams',note:'A smooth, durable furniture paint finish for high-touch pieces.',use:'Finish · paint',url:'https://www.sherwin-williams.com/homeowners/products/emerald-urethane-trim-enamel'},
  {id:'topcoat',name:'Polycrylic Protective Finish',brand:'Minwax',note:'A clear protective layer for a piece that needs extra durability.',use:'Protect · topcoat',url:'https://www.minwax.com/en/products/protective-finishes/polycrylic-protective-finish'},
  {id:'sprayer',name:'Flexio 5000 Paint Sprayer',brand:'Wagner',note:'Helpful for an even finish on larger furniture projects.',use:'Finish · tool',url:'https://www.wagnerspraytech.com/products/paint-sprayers/flexio-5000/'},
  {id:'sander',name:'Random Orbit Sander',brand:'Bosch',note:'Makes surface prep faster and more consistent.',use:'Prep · tool',url:'https://www.boschtools.com/us/en/products/ros10-0601375001'}
];

function App(){
  const [screen,setScreen]=useState('home');
  const [type,setType]=useState('Dresser'); const [source,setSource]=useState('Facebook Marketplace'); const [price,setPrice]=useState('40');
  const [answers,setAnswers]=useState({style:'Mid-century / clean lines',material:'Solid wood or veneer',condition:'Minor cosmetic wear',construction:'Sturdy and stable'});
  const [makeover,setMakeover]=useState('Paint + natural wood'); const [surface,setSurface]=useState('Previously finished wood'); const [issues,setIssues]=useState(['Scratches']);
  const [tasks,setTasks]=useState({'0-0':true,'0-1':true,'1-0':true,'1-1':true,'1-2':true,'2-0':true,'2-1':true,'2-2':true,'3-0':true,'3-1':true,'3-2':true,'4-0':true});
  const [detail,setDetail]=useState(4); const [owned,setOwned]=useState([]); const [listing,setListing]=useState(false); const [copied,setCopied]=useState(false); const [saved,setSaved]=useState(false); const [sellChecks,setSellChecks]=useState([]);
  const go=(s)=>{setScreen(s);window.scrollTo({top:0,behavior:'smooth'});};
  const projectName=type==='Nightstands'?'Nightstand Set':type==='Dresser'?'Mid-Century Dresser':type;
  const doneCount=phases.filter((p,i)=>p.tasks.every((_,j)=>tasks[`${i}-${j}`])).length;
  const score = Math.max(36,Math.min(95,82 + (answers.material==='Particle board / MDF'?-18:0) + (answers.condition==='Major repairs needed'?-18:0) + (answers.construction==='Wobbly or damaged'?-16:0) + (answers.style==='Very ornate / niche'?-8:0)));
  const purchase=Number(price)||0, low=Math.max(110,Math.round((purchase+235)/25)*25), high=low+100, supplies=35;
  const recommendedProducts=makeover==='Restore the wood' ? products.filter(p=>['sander','topcoat'].includes(p.id)) : makeover==='Paint it' ? products : products;
  const toggleIssue=(v)=>setIssues(issues.includes(v)?issues.filter(x=>x!==v):[...issues,v]);
  const toggleTask=(i,j)=>setTasks({...tasks,[`${i}-${j}`]:!tasks[`${i}-${j}`]});
  const toggleOwned=(id)=>setOwned(owned.includes(id)?owned.filter(x=>x!==id):[...owned,id]);
  const title=(eyebrow,heading,sub)=> <div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{heading}</h1>{sub&&<p>{sub}</p>}</div>;
  const pageHero=(photo,caption,alt)=> <figure className="page-hero"><img src={`/images/heroes/${photo}.jpg`} alt={alt}/><figcaption>{caption}</figcaption></figure>;
  const tip=(copy)=> <div className="tip"><div className="tip-icon"><Lightbulb size={17}/></div><div><strong>Catie’s Tip</strong><p>{copy}</p></div></div>;
  const button=(label,onClick,variant='primary',icon=true)=> <button className={`button ${variant}`} onClick={onClick}>{label}{icon&&<ArrowRight size={18}/>}</button>;
  const back=(target)=> <button className="back" onClick={()=>go(target)}><ArrowLeft size={18}/> Back</button>;
  const choice=(value,selected,onClick,withImage=false)=> <button key={value} className={`choice ${selected?'selected':''} ${withImage?'with-image':''}`} aria-pressed={selected} onClick={onClick}>{withImage&&<img className="choice-icon" src={`/images/choices/${choiceImages[value]}.png`} alt=""/>}<span className="choice-label">{value}</span><span className="radio">{selected&&<Check size={13}/>}</span></button>;

  return <div className="site"><div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>go('home')} aria-label="Go home"><span className="brand-mark">m<span>✦</span></span><span>miss mae <em>revivals</em><small>FLIP COMPANION</small></span></button><button className="header-action" onClick={()=>go('flips')} aria-label="My flips"><Menu size={23}/></button></header>
    <main key={screen} className="content">
    {screen==='home'&&<>
      <section className="hero"><div className="hero-copy"><span className="eyebrow light">YOUR CREATIVE SIDEKICK</span><h1>Ready to flip<br/><i>something?</i></h1><p>From “should I buy it?” to “sold!” — a little guidance for every step.</p>{button('Start a New Flip',()=>go('new'),'cream')}</div><div className="hero-image"><img src={IMAGE} alt="Refinished mid-century dresser in a warm room"/></div></section>
      <div className="section-heading"><div><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>Your current flip</h2></div><button className="text-link" onClick={()=>go('flips')}>View all <ArrowRight size={15}/></button></div>
      <button className="project-card" onClick={()=>go('plan')}><img src={IMAGE} alt={saved?projectName:'Mid-Century Dresser'}/><div><span className="mini-label">IN PROGRESS</span><h3>{saved?projectName:'Mid-Century Dresser'}</h3><p>Refinishing · {doneCount} of 7 steps complete</p><div className="progress"><span style={{width:`${doneCount/7*100}%`}}/></div><span className="continue">Continue your flip <ArrowRight size={16}/></span></div></button>
      <div className="section-heading help-head"><div><span className="eyebrow">A LITTLE HELP, RIGHT ON TIME</span><h2>Quick help</h2></div></div><div className="help-grid">{[['Is this piece worth buying?','evaluation'],['What supplies do I need?','supplies'],['How should I refinish this?','makeover'],['How should I price it?','sell']].map(([q,s],i)=><button className="help-card" key={q} onClick={()=>go(s)}><span className="help-number">0{i+1}</span><strong>{q}</strong><ArrowRight size={18}/></button>)}</div>
      <div className="home-note"><Sparkles size={18}/><span>Made for the magic in the messy middle.</span></div>
    </>}
    {screen==='new'&&<>{back('home')}{title('LET’S GET STARTED','Tell me about your find.','Every great flip starts with seeing the potential.')}{pageHero('found-dresser','A FIND WITH POTENTIAL','Vintage wood dresser waiting to be refinished')}
      <div className="form-section"><div className="question-head"><span>01</span><h2>What are you flipping?</h2></div><div className="choice-grid">{types.map(v=>choice(v,type===v,()=>setType(v),true))}</div></div>
      <div className="form-section"><div className="question-head"><span>02</span><h2>Where did you find it?</h2></div><div className="choice-grid">{sources.map(v=>choice(v,source===v,()=>setSource(v),true))}</div></div>
      <div className="form-section"><div className="question-head"><span>03</span><h2>What’s the purchase price?</h2></div><label className="price-input"><span>$</span><input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} aria-label="Purchase price"/><small>USD</small></label><p className="field-hint">Free find? Enter $0.</p></div>{button('Evaluate This Piece',()=>go('evaluation'))}</>}
    {screen==='evaluation'&&<>{back('new')}{title('BUY THIS, NOT THAT','Is it a good flip?','Catie’s four checkpoints help you spot the pieces worth your time.')}{pageHero('found-dresser','LOOK CLOSER BEFORE YOU BUY','Vintage dresser with visible wear at a thrift shop')}
      <div className="eval-intro"><div className="intro-icon"><ClipboardList size={22}/></div><div><strong>The quick flip check</strong><p>Choose what best describes your {type.toLowerCase()}.</p></div></div>
      {[['style','Style',['Mid-century / clean lines','Vintage / classic','Very ornate / niche']],['material','Material',['Solid wood or veneer','Quality laminate','Particle board / MDF']],['condition','Condition',['Minor cosmetic wear','Some repair needed','Major repairs needed']],['construction','Construction',['Sturdy and stable','Needs a little tightening','Wobbly or damaged']]].map(([key,label,opts],i)=><div className="eval-group" key={key}><div className="question-head"><span>0{i+1}</span><h2>{label}</h2></div><div className="stacked-choices">{opts.map(v=>choice(v,answers[key]===v,()=>setAnswers({...answers,[key]:v})))}</div></div>)}
      <div className="result-card"><div className="result-top"><span><Sparkles size={17}/> {score>=65?'GOOD FLIP POTENTIAL':'THINK IT THROUGH'}</span><strong>{score}<small>/100</small></strong></div><h2>{score>=65?'This piece has promise.':'This one may need extra work.'}</h2><p>Based on your answers and a sample resale estimate.</p><div className="result-figures"><div><span>Purchase</span><strong>${purchase}</strong></div><div><span>Supplies</span><strong>~$35</strong></div><div><span>Suggested resale</span><strong>${low}–${high}</strong></div><div><span>Potential gross profit</span><strong>${Math.max(0,low-purchase-supplies)}–${Math.max(0,high-purchase-supplies)}</strong></div></div><small className="estimate-note">Illustrative estimates. Actual costs and sale price vary.</small></div>
      {button('Add to My Flips',()=>{setSaved(true);setTasks({'0-0':true,'0-1':true});go('makeover')})}</>}
    {screen==='makeover'&&<>{back('evaluation')}{title('MAKEOVER DIRECTION','What’s the vision?','Pick a direction. Your plan will adapt to the finish you choose.')}
      {pageHero('workshop','THE POSSIBILITIES ARE GOOD','Dresser being carefully sanded in a home workshop')}<div className="form-section"><div className="question-head"><span>01</span><h2>Choose a makeover</h2></div><div className="stacked-choices">{['Restore the wood','Paint it','Paint + natural wood','Not sure'].map(v=>choice(v,makeover===v,()=>setMakeover(v)))}</div></div><div className="form-section"><div className="question-head"><span>02</span><h2>What’s the current surface?</h2></div><div className="choice-grid">{['Previously finished wood','Bare wood','Previously painted','Laminate / other'].map(v=>choice(v,surface===v,()=>setSurface(v)))}</div></div><div className="form-section"><div className="question-head"><span>03</span><h2>Any problem spots?</h2></div><p className="field-hint top">Select all that apply.</p><div className="chip-grid">{problems.map(v=><button key={v} className={`chip ${issues.includes(v)?'active':''}`} onClick={()=>toggleIssue(v)}>{issues.includes(v)&&<Check size={14}/>} {v}</button>)}</div></div>{tip('A good makeover works with the piece. When the wood has beautiful grain, consider letting some of it shine.')}{button('Generate My Flip Plan',()=>go('plan'))}</>}
    {screen==='plan'&&<>{back('flips')}{title('YOUR PERSONAL ROADMAP',`Your ${type} Flip Plan`,'One manageable step at a time. You’ve got this.')}{pageHero('workshop','FROM FIND TO FINISH','Furniture restoration in progress at a home workshop')}
      <div className="plan-summary"><div><span className="eyebrow light">PROJECT PROGRESS</span><h2>{doneCount} of 7 steps<br/>complete</h2></div><div className="ring" style={{'--progress':`${doneCount/7*100}%`}}><span>{Math.round(doneCount/7*100)}%</span></div><div className="plan-progress"><span style={{width:`${doneCount/7*100}%`}}/></div></div>
      <div className="path-label">YOUR PATH FROM FIND TO FINISH</div><div className="phase-list">{phases.map((p,i)=>{const complete=p.tasks.every((_,j)=>tasks[`${i}-${j}`]);return <div className="phase-card" key={p.name}><button className="phase-main" onClick={()=>{setDetail(i);go(i===6?'sell':'detail')}}><span className={`phase-number ${complete?'complete':''}`}>{complete?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><span className="phase-copy"><small>{p.kicker}</small><strong>{p.name}</strong></span><span className="phase-count">{p.tasks.filter((_,j)=>tasks[`${i}-${j}`]).length}/{p.tasks.length}</span><ChevronRight size={18}/></button><div className="phase-tasks">{p.tasks.map((task,j)=><label key={task} className="task"><input type="checkbox" checked={!!tasks[`${i}-${j}`]} onChange={()=>toggleTask(i,j)}/><span className="check-box"><Check size={13}/></span><span>{task}</span></label>)}</div>{i===1&&tip(p.tip)}{i===3&&<button className="inline-supply" onClick={()=>go('supplies')}><ShoppingBag size={16}/> See recommended finish supplies <ArrowRight size={15}/></button>}</div>})}</div><div className="plan-end">{button('View Supplies for This Flip',()=>go('supplies'),'outline')}{button('Get Ready to Sell',()=>go('sell'))}</div></>}
    {screen==='detail'&&<>{back('plan')}<div className="detail-tag">STEP {String(detail+1).padStart(2,'0')} OF 07</div>{title(phases[detail].kicker.toUpperCase(),phases[detail].name,`A practical guide to the ${phases[detail].name.toLowerCase()} stage.`)}{pageHero(detail === 0 ? 'found-dresser' : detail >= 5 ? 'finished-dresser' : detail >= 3 ? 'supplies' : 'workshop',`${phases[detail].name.toUpperCase()} IN PROGRESS`, 'Furniture flipping project at this stage')}<div className="time-card"><span>ESTIMATED ACTIVE TIME</span><strong>{phases[detail].time}</strong></div><div className="detail-section"><h2>Here’s what to do</h2><p>{detail===1?'Start by removing hardware, then clean the entire piece with a suitable cleaner. Once dry, lightly scuff the finish so your next coat can grip. Wipe away all dust before moving on.':detail===3?`For your ${makeover.toLowerCase()} finish, work in thin, even coats. Test products on a hidden area first and follow each product’s dry time before adding the next coat.`:`Work through these small tasks in order. Check each one off as you go, and take a quick progress photo before moving to the next stage.`}</p><div className="detail-checklist">{phases[detail].tasks.map((t,j)=><label className="task" key={t}><input type="checkbox" checked={!!tasks[`${detail}-${j}`]} onChange={()=>toggleTask(detail,j)}/><span className="check-box"><Check size={13}/></span><span>{t}</span></label>)}</div></div>{tip(phases[detail].tip)}{[1,3,4].includes(detail)&&<div className="detail-section"><h2>Good to have nearby</h2><div className="mini-products">{products.filter(p=>detail===1?['sander'].includes(p.id):detail===3?['primer','paint','sprayer'].includes(p.id):p.id==='topcoat').map(p=><button key={p.id} onClick={()=>go('supplies')}><img src={`/images/${p.id}.png`} alt=""/><span>{p.name}</span><ChevronRight size={16}/></button>)}</div></div>}<div className="video-placeholder"><div className="play-circle"><Play size={22} fill="currentColor"/></div><span>VIDEO LESSON PREVIEW</span><strong>{phases[detail].name} with Catie</strong><small>Full lesson available in the course</small></div><div className="course-card"><span className="eyebrow">GO DEEPER WITH CATIE</span><h2>Want the full lesson?</h2><p>This topic is covered inside The Busy Parent Flip System.</p><a className="button primary" href={courseUrl} target="_blank" rel="noopener noreferrer">Open My Course <ArrowRight size={18}/></a></div>{button(detail===6?'Go to Selling Guide':'Next Step',()=>{if(detail===6)go('sell');else {setDetail(detail+1);go('detail')}})}</>}
    {screen==='supplies'&&<>{back('plan')}{title('THE GOOD STUFF','Supplies for your flip.','A short, practical list inspired by Miss Mae Revivals Favorites.')}{pageHero('supplies','TOOLS FOR THE TRANSFORMATION','Sander, paint, brushes and other furniture refinishing supplies')}
      <div className="supply-banner"><ShoppingBag size={22}/><div><strong>For your {makeover.toLowerCase()} makeover</strong><p>{surface} · {issues.length?issues.join(', '):'No major issues noted'}</p></div></div><div className="filter-title">RECOMMENDED FOR THIS PROJECT <span>{recommendedProducts.length} items</span></div><div className="product-list">{recommendedProducts.map(p=><article className="product-card" key={p.id}><div className="product-image"><img src={`/images/${p.id}.png`} alt={p.name}/></div><div className="product-copy"><span className="mini-label">{p.use}</span><h2>{p.name}</h2><small>{p.brand}</small><p>{p.note}</p><div className="product-actions"><a href={p.url} target="_blank" rel="noopener noreferrer">View Product <ArrowRight size={15}/></a><button onClick={()=>toggleOwned(p.id)}>{owned.includes(p.id)?<CheckCircle2 size={15}/>:<Plus size={15}/>} {owned.includes(p.id)?'In my kit':'Already Have This'}</button></div></div></article>)}</div><p className="affiliate">Some product links may be affiliate links. Recommendations are sample content for this prototype.</p>{button('Back to My Flip Plan',()=>go('plan'),'outline')}</>}
    {screen==='sell'&&<>{back('plan')}{title('THE FINISH LINE','Let’s get it sold.','Turn your hard work into a listing buyers will love.')}{pageHero('finished-dresser','READY FOR ITS NEXT HOME','Finished dresser styled for a furniture listing')}
      <div className="sell-hero"><span className="eyebrow light">YOUR FLIP AT A GLANCE</span><h2>{projectName}</h2><div className="money-row"><div><span>Purchase</span><strong>${purchase}</strong></div><div><span>Supplies</span><strong>$35</strong></div><div><span>Total investment</span><strong>${purchase+35}</strong></div></div><div className="resale-row"><div><span>Suggested resale</span><strong>${low}–${high}</strong></div><div><span>Estimated profit</span><strong>${Math.max(0,low-purchase-35)}–${Math.max(0,high-purchase-35)}</strong></div></div><small>Sample estimates, before platform fees or other costs.</small></div>
      <div className="detail-section"><h2>Ready-to-list checklist</h2><div className="detail-checklist">{['Final quality check','Clean hardware','Stage furniture','Take photos','Create listing','Set asking price'].map((v,i)=><label className="task" key={v}><input type="checkbox" checked={sellChecks.includes(i)} onChange={()=>setSellChecks(sellChecks.includes(i)?sellChecks.filter(x=>x!==i):[...sellChecks,i])}/><span className="check-box"><Check size={13}/></span><span>{v}</span></label>)}</div></div>{tip('A clean, well-lit photo and a clear title can do a lot of the selling for you. Include dimensions and note any imperfections honestly.')}{button('Help Me Create My Listing',()=>setListing(true))}{listing&&<div className="listing-card"><div className="listing-top"><span><Sparkles size={17}/> SAMPLE MARKETPLACE LISTING</span><button onClick={()=>setListing(false)} aria-label="Close listing"><X size={17}/></button></div><label>Title</label><h2>Refinished {projectName} | Solid, Stylish Storage</h2><label>Description</label><p>Beautifully refreshed {projectName.toLowerCase()} with a {makeover.toLowerCase()} finish. Sturdy construction, smooth-working drawers, and plenty of useful storage. Carefully cleaned, prepped, and finished. A lovely statement piece for a bedroom or living space.</p><p>Approx. asking price: ${high}. Please message for dimensions, pickup details, or additional photos.</p><button className="copy-button" onClick={()=>{navigator.clipboard?.writeText(`Refinished ${projectName} | Solid, Stylish Storage\n\nBeautifully refreshed ${projectName.toLowerCase()} with a ${makeover.toLowerCase()} finish. Sturdy construction, smooth-working drawers, and plenty of useful storage. Carefully cleaned, prepped, and finished. Asking $${high}. Message for dimensions, pickup details, or photos.`);setCopied(true)}}>{copied?'Copied!':'Copy listing text'}</button></div>}</>}
    {screen==='flips'&&<>{title('YOUR CREATIVE TRACK RECORD','My Flips','Every piece has a story. Here are yours.')}{pageHero('finished-dresser','EVERY FLIP HAS A STORY','Refinished dresser staged in a living room')}{button('Start a New Flip',()=>go('new'))}<div className="section-heading"><div><span className="eyebrow">CURRENT PROJECT</span><h2>In the works</h2></div></div><button className="flip-tile" onClick={()=>go('plan')}><img src={IMAGE} alt="Mid-Century Dresser"/><div><span className="mini-label">ACTIVE FLIP</span><h3>{saved?projectName:'Mid-Century Dresser'}</h3><p>{doneCount}/7 steps complete</p><div className="progress"><span style={{width:`${doneCount/7*100}%`}}/></div></div><ChevronRight size={18}/></button><div className="section-heading"><div><span className="eyebrow">A LITTLE PROOF IT’S POSSIBLE</span><h2>Finished & sold</h2></div></div><div className="completed-card"><div className="completed-art"><span>MM</span></div><div><span className="mini-label">SOLD</span><h3>Nightstand Set</h3><p>Bought: $30 · Sold: $285</p><strong>$210 profit</strong></div><CheckCircle2 size={20}/></div></>}
    {screen==='learn'&&<>{title('LEARN WITH CATIE','A little more know-how.','Helpful lessons for whatever stage you’re in.')}{pageHero('workshop','SKILLS FOR EVERY STAGE','Hands refinishing a dresser in a warm home workshop')}
      <div className="learn-hero"><BookOpen size={27}/><span className="eyebrow light">THE BUSY PARENT FLIP SYSTEM</span><h2>The whole process,<br/>in one place.</h2><p>Deepen your skills with Catie’s complete video course on sourcing, prepping, painting, and selling furniture.</p><a className="button cream" href={courseUrl} target="_blank" rel="noopener noreferrer">Explore the Course <ArrowRight size={18}/></a></div><div className="section-heading"><div><span className="eyebrow">EXPLORE A TOPIC</span><h2>Quick lessons</h2></div></div>{[['Buy This, Not That','What makes a great flip?',()=>go('evaluation')],['Prep before paint','The foundation of a lasting finish',()=>{setDetail(1);go('detail')}],['Finish with confidence','Make your makeover shine',()=>{setDetail(3);go('detail')}],['Price for profit','Know your numbers before you list',()=>go('sell')]].map(([h,p,fn],i)=><button className="learn-row" key={h} onClick={fn}><span>0{i+1}</span><div><strong>{h}</strong><small>{p}</small></div><ChevronRight size={18}/></button>)}</>}
    </main>
    <nav className="bottom-nav" aria-label="Main navigation">{[['Home','home',Home],['My Flips','flips',Heart],['Learn','learn',BookOpen],['Supplies','supplies',ShoppingBag]].map(([label,s,Icon])=><button key={s} className={screen===s?'active':''} onClick={()=>go(s)}><Icon size={21} strokeWidth={screen===s?2.5:1.9}/><span>{label}</span></button>)}</nav>
  </div><div className="desktop-aside"><span>MISS MAE REVIVALS</span><h2>Find it.<br/>Flip it.<br/><i>Love it.</i></h2><p>Your hands-on companion for turning a promising find into a beautiful, profitable flip.</p><div className="aside-rule"/><small>THE FLIP COMPANION · INTERACTIVE PROTOTYPE</small></div></div>
}

createRoot(document.getElementById('root')).render(<App/>);
